### ISSUE TITLE
Manage Organization Blazor page Error

### ISSUE THREAD

**Issue by pokrad** [lucent-sea/Remotely#289] opened 2021-04-17 15:31 UTC
Hi !

After publishing Server to the IIS and creating user (first user in the system), some pages are not working.
When navigating to "Organitation" I am getting error:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Remotely_Server
  StackTrace:
   at Remotely.Server.Pages.ManageOrganization.BuildRenderTree(RenderTreeBuilder __builder) in D:\Remotely\Server\Pages\ManageOrganization.razor:line 9

Further investigation shows that "@_organization" member is NULL in the time when page is rendering.
I think that it has something to do with the fact that RefreshData method is called as async, and meanwhile server continues to render page. In the moment when blazor page is rendered, data from "RefreshData" is not there yet.

Again, not exactly part of technology I used before, but quick investigation shows some "suggestions":

https://stackoverflow.com/questions/58371328/oninitializedasync-in-blazor
and a few more tricks that are possible:
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1#stateful-reconnection-after-prerendering

I am suggesting the following patch:

diff --git a/Server/Pages/ManageOrganization.razor b/Server/Pages/ManageOrganization.razor
index 02db1dff..225fc653 100644
--- a/Server/Pages/ManageOrganization.razor
+++ b/Server/Pages/ManageOrganization.razor
@@ -5,7 +5,7 @@
 <h3 class="mb-3">Manage Organization</h3>
 
 
-@if (User.IsAdministrator)
+@if (User.IsAdministrator && _isDataReady)
 {
 
     <div class="row">

diff --git a/Server/Pages/ManageOrganization.razor.cs b/Server/Pages/ManageOrganization.razor.cs
index a221336d..284c4c22 100644
--- a/Server/Pages/ManageOrganization.razor.cs
+++ b/Server/Pages/ManageOrganization.razor.cs
@@ -28,6 +28,7 @@ namespace Remotely.Server.Pages
         private string _newDeviceGroupName;
         private Organization _organization;
         private string _selectedDeviceGroupId;
+        private Boolean _isDataReady = false;
 
         [Inject]
         private IDataService DataService { get; set; }
@@ -228,6 +229,7 @@ namespace Remotely.Server.Pages
             _invites.AddRange(DataService.GetAllInviteLinks(Username).OrderBy(x => x.InvitedUser));
             _deviceGroups.AddRange(DataService.GetDeviceGroups(Username).OrderBy(x => x.Name));
             _orgUsers.AddRange(DataService.GetAllUsersInOrganization(Username).OrderBy(x => x.UserName));
+            _isDataReady = true;
         }
         private async Task ResetPassword(RemotelyUser user)
         {

At least that was enough for me to make it work...

Regards !

**Comment by pokrad** [comment] 2021-04-17 15:36
Sorry, I was not aware that editor will mess up the patch :)
[BlazorPatch.txt](https://github.com/lucent-sea/Remotely/files/6329529/BlazorPatch.txt)

**Comment by lucent-sea** [comment] 2021-04-17 15:48
Heya!

Thanks for the report.  I was actually already working on it this morning.  :)  I pushed the changes up to master if you want to try them out:  https://github.com/lucent-sea/Remotely/commit/4120faa560e40ca74836bf07360df15e772e5a6a

A little more context into what's going on.  Initially, methods/properties in `AuthComponentBase` and `AuthService` were synchronous by design.  I was trying to set it up so any components that inherited `AuthComponentBase` would block until the auth data was loaded.

I assumed it was working, but apparently it was only okay with that in SQLite.  :D

Anyhow, I guess that was a dumb approach.  So I've made it async all the way through, with null conditional operators where data might not be loaded yet.

If I've missed any in the latest code, let me know!  :)

**Comment by pokrad** [comment] 2021-04-17 15:51
Just figured out that even simpler way is to just put:

@if (User.IsAdministrator && (_organization!=null))

in the render part :)

That way it works whatever reason for not getting _organization is :)

Will try to fetch fresh copy and try :)

**Comment by pokrad** [comment] 2021-04-17 16:02
From a fresh copy, got an error saying the user is null :)
This solved the issue:

return user?.UserOptions?.Theme ?? _appConfig.Theme;

in function:

        public async Task<Theme> GetEffectiveTheme()
        {
            if (await _authService.IsAuthenticated())
            {
                var user = await _authService.GetUser(); 
                return user?.UserOptions?.Theme ?? _appConfig.Theme;
            }
            return _appConfig.Theme;
        }

**Comment by lucent-sea** [comment] 2021-04-17 18:38
Thanks.  I pushed a fix for that, as well as more areas that needed fixing.  I'll wait to hear back from you.  :)

**Comment by pokrad** [comment] 2021-04-18 16:45
Deploy on IIS now passes for all database types (SqlLite, Postgres, MSSQL).
And I can create admin user and administer the server without issues ( so far ;) )
 Thanks !

Now I have some question about build configurations, but I'll open another thread with more details...

**Comment by lucent-sea** [comment] 2021-04-18 19:52
Thanks for testing and reporting back! 🙏

**Closed by lucent-sea** 2021-04-18 19:52 UTC
