### ISSUE TITLE
Crash on startup w/ clean PostgreSQL database

### ISSUE THREAD

**Issue by chasekidder** [lucent-sea/Remotely#202] opened 2021-01-08 20:12 UTC
Hi, just wanted to put this on the radar. There seems to be an issue with the latest release (v2021.01.04.1928) and initializing a new database in PostgreSQL 11.

### Environment:
- OS: Debian GNU/Linux 9 (stretch)
- Kernel: 4.19.98-Unraid
- Database Version: PostgreSQL 11.10 (Debian 11.10-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
- Software Version: Remotely v2021.01.04.1928 Linux_x64

### Description:
Remotely crashes with the error ```operator does not exist: text < timestamp with time zone``` when using a fresh PostgreSQL database. Similar issue to #136 . Solution described there did not resolve the issue. Dropping the database and using latest version produced the same error.

### Workaround:
I was able to get Remotely working by initializing the database with an older version of Remotely (v2020.10.14.1849) to build the database and then updating to the latest version (v2021.01.04.1928).

### Log:
```
SqlState: 42883
MessageText: operator does not exist: text < timestamp with time zone
Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
Position: 148
File: parse_oper.c
Line: 731
Routine: op_error
Application startup exception: Npgsql.PostgresException (0x80004005): 42883: operator does not exist: text < timestamp with time zone
at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
at Npgsql.NpgsqlDataReader.NextResult()
at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
at System.Data.Common.DbCommand.ExecuteReader()
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
at Microsoft.EntityFrameworkCore.DbContext.RemoveRange(IEnumerable`1 entities)
at Remotely.Server.Services.DataService.CleanupOldRecords() in C:\ProgramData\BuildAgent\_work\1\s\Server\Services\DataService.cs:line 309
at Remotely.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ApplicationDbContext context, DataService dataService, ILoggerFactory loggerFactory) in C:\ProgramData\BuildAgent\_work\1\s\Server\Startup.cs:line 242
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Exception data:
Severity: ERROR
```

**Comment by lucent-sea** [comment] 2021-01-15 15:47
I wasn't able to reproduce this in PostgreSQL 13.

**Comment by sinichi19** [comment] 2021-01-16 06:58
dont know if this is the same problem also try to change the database to postgres but after the fresh install of PostSQL and created database named remotely and grant all privileges to postgres and change the DBProvider to PostgreSQL after the restart the server cant load the remotely with display Internal Server error / restored the default appsettings will load normaly again,

**Comment by sinichi19** [comment] 2021-01-16 12:24
@chasekidder  hi sir requesting for your kind assistance can you please share post the command how you able to change the sqlite to postgre .. 

thank you

**Comment by chasekidder** [comment] 2021-01-16 20:13
> @chasekidder hi sir requesting for your kind assistance can you please share / post the command how you able to change the sqlite to postgre ..
> 
> thank you

The [Configuration](https://github.com/lucent-sea/Remotely#configuration) section of the readme has the information you need. Create an appsettings.Production.json file and edit the ConnectionStrings to include your Postgres DB info so it looks something like this:
`"ConnectionStrings": {
    ...
    "PostgreSQL": "Host=xxx.xxx.xxx.xxx;Port=xxxx;Database=remotely;Username=remotely;Password=remotely;",
    ...
  },`

Then you can select Postrges as the DBProvider in the ApplicationOptions section.
`"ApplicationOptions": {
    ...
    "DBProvider": "PostgreSQL",
    ...
  }`

**Comment by sinichi19** [comment] 2021-01-16 23:57
@chasekidder  ohh the password is missing on my settings will try this. thank you sir

**Comment by lucent-sea** [comment] 2021-01-17 19:12
@chasekidder Do you have the bandwidth to test a fresh install on PostgreSQL 13?

**Comment by sinichi19** [comment] 2021-01-18 01:27
@lucent-sea I confirmed working postgresSQL13 without problem. I already changed the database

Also thank you Sir @chasekidder  for complete details how can i change the database

**Comment by lucent-sea** [comment] 2021-01-22 14:41
Closing this for now since it can't be reproduced on Postgres 13.

**Closed by lucent-sea** 2021-01-22 14:41 UTC

**Comment by sinichi19** [comment] 2021-02-07 05:02
@chasekidder  sir regarding to your workaround hows your remotely server using postgresql-11 how many connections you have.
